### PR TITLE
Update project to support Python 3.14

### LINKED ISSUE #2137: [FEATURE]: Support python 3.14
### Problem statement

Python 3.14 has been released, and our documentation states that prior to installation:
> Verify that Python 3.10 or above is installed

However some of our dependencies do not support Python 3.14 at the moment. Problems include:

 - `install-tranpsiler` fails due to an import issues.
 - The BB plugin has code that is specific to platform and python version. Currently there is nothing in place for Python 3.14, which means it will not work.
 - Some (transitive) dependencies do not have wheels published for all platforms. For example, user reports suggest there are problems with `duckdb` and `pyodbc` on Windows.

(There might be more problems than just this.)

### Proposed Solution

In the short term:

 - Update the documentation to mention that Python 3.14 doesn't currently work.

In the medium term:

 - Update the project (including BB) to work with Python 3.14.

### Additional Context

Import issue during `install-transpile`:
```
20:03:56 Debug: starting: /Users/**REDACTED**/dev/lakebridge/.venv/bin/python3 /Users/**REDACTED**/dev/lakebridge/src/databricks/labs/lakebridge/cli.py {"command":"install-transpile","flags":{"artifact":"","include-llm-transpiler":"false","interactive":"auto","log_level":"debug"},"output_type":""} pid=83223
Traceback (most recent call last):
  File "/Users/**REDACTED**/dev/lakebridge/src/databricks/labs/lakebridge/cli.py", line 27, in <module>
    from databricks.labs.lakebridge.contexts.application import ApplicationContext
  File "/Users/**REDACTED**/dev/lakebridge/src/databricks/labs/lakebridge/contexts/application.py", line 21, in <module>
    from databricks.labs.lakebridge.deployment.installation import WorkspaceInstallation
  File "/Users/**REDACTED**/dev/lakebridge/src/databricks/labs/lakebridge/deployment/installation.py", line 15, in <module>
    from databricks.labs.lakebridge.deployment.recon import ReconDeployment
  File "/Users/**REDACTED**/dev/lakebridge/src/databricks/labs/lakebridge/deployment/recon.py", line 15, in <module>
    from databricks.labs.lakebridge.deployment.table import TableDeployment
  File "/Users/**REDACTED**/dev/lakebridge/src/databricks/labs/lakebridge/deployment/table.py", line 2, in <module>
    from importlib.abc import Traversable
ImportError: cannot import name 'Traversable' from 'importlib.abc' (/opt/homebrew/Cellar/python@3.14/3.14.0_1/Frameworks/Python.framework/Versions/3.14/lib/python3.14/importlib/abc.py)
Error: exit status 1
```
(Looks trivial.)

### PR DESCRIPTION
**Pull request by asnare**
### What does this PR do?

This PR updates this project so that the CLI supports Python 3.14. Aside the from the project metadata, this involved:

 - Updating to current versions of `mypy`, `pylint` and `pytest` that work properly with python 3.14. Some code-changes were required to satisfy the new versions of these tools.
 - Expands both unit and integration testing to cover all supported python versions.

### Relevant implementation details

Downstream dependencies already been released with support for Python 3.14:

 - Blueprint
 - Bladebridge

The `pytester` and `lsql` dependencies already work with python 3.14, although the project metadata may not reflect this.

A further improvement here is integration testing across the python version matrix. 

### Caveats/things to watch out for when reviewing:

We have our first system imports that depend on the version of python:

 - `importlib.abc.Traversable` was moved to `importlib.abs.resources.Traversable` in Python 3.11, with the old location deprecated and removed in 3.14.
 - An import-guard based on the python version is the only way to both ensure the import works _and_ that mypy is aware of which import is currently active.

Due to the expanded unit and integration tests, the set of mandatory checks on PRs for this repository will need to be adjusted.

### Linked issues

Resolves #2137.

### Functionality

- updated relevant user documentation
- modifies existing commands:

   - `databricks labs install lakebridge`
   - `databricks labs lakebridge install-transpile`
   - etc. 

### Tests

- manually tested
- existing unit tests, extended to cover python 3.14.
- existing integration tests, extended to cover all supported python versions.

### CODE REVIEW

File: pyproject.toml [hunk 1]
```diff
@@ -119,10 +125,32 @@ dependencies = [
   "sqlglot",
 ]
 
+[tool.hatch.envs.test.env-vars]
+MYPY_CACHE_DIR = ".venv-py{matrix:python}/mypy-cache"
+PYTEST_ADDOPTS = "-o cache_dir=.venv-py{matrix:python}/pytest-cache"
+RUFF_CACHE_DIR = ".venv-py{matrix:python}/ruff-cache"
```
Comment (m-abulazm) [inline pyproject.toml]: wow. didnt know that is possible

File: .codegen.json [hunk 2]
```diff
@@ -4,8 +4,11 @@
   },
   "toolchain": {
     "required": ["hatch"],
-    "pre_setup": ["hatch env create"],
-    "prepend_path": ".venv/bin",
+    "pre_setup": [
+      "hatch env create \"${HATCH_ENV:-default}\"",
+      "ln -sfn \"$(hatch env find \"${HATCH_ENV:-default}\")\" .venv-py3.xx"
+    ],
```
Comment (m-abulazm) [inline .codegen.json]: please add a short comment to explain

**Review by m-abulazm — APPROVED** [review]
LGTM

File: docs/lakebridge/docs/installation.mdx [hunk 3]
```diff
@@ -85,18 +85,16 @@ databricks configure --host <host> --profile <profile_name>
 
 #### 2.1 Python
 
-**Version Required:** Python between 3.10.1 and 3.13.x (inclusive).
+**Version Required:** Python between 3.10.1 and 3.14.x (inclusive).
 
-- **Windows** - Install python from [here](https://www.python.org/downloads/).
+- **Windows** - Install python from [here](https://www.python.org/downloads/). (XXX use the 64-bit version)
```
Comment (sundarshankar89) [inline docs/lakebridge/docs/installation.mdx]: small clarification, did you mean the XXX to indicate the version number?

**Review by sundarshankar89 — APPROVED** [review]
LGTM with small clarification.

File: docs/lakebridge/docs/installation.mdx (hunk 3 above)
Comment (asnare) [reply docs/lakebridge/docs/installation.mdx]: My bad, that was a marker for myself to flag that an update was needed; I've just fixed this by updating the text here.

File: .codegen.json (hunk 2 above)
Comment (asnare) [reply .codegen.json]: This was dropped because we've moved to uv.
